Description: |
  only Ec2KeyName is required parameter
  creates security group, ec2 

Parameters:
  Ec2InstanceType:
    Type: String
    Default: c7g.4xlarge # building custom iosevka font requires quite lot of computing resource!

  Ec2AmiId:
    Type: String
    Default: ami-0771ec94d0241c207 # arm

  Ec2KeyName:
    Type: String
    Default: foo_key_pair

Resources:
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow minimal access for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref Ec2InstanceType
      ImageId: !Ref Ec2AmiId
      KeyName: !Ref Ec2KeyName
      SecurityGroupIds:
        - !Ref Ec2SecurityGroup

Outputs:
  Ec2SecurityGroupId:
    Description: Physical ID of the EC2 Security Group
    Value: !Ref Ec2SecurityGroup
  Ec2InstanceId:
    Description: Physical ID of the EC2 Instance
    Value: !Ref Ec2Instance
  Ec2PublicIp:
    Description: Ec2 public ip
    Value: !GetAtt Ec2Instance.PublicIp
    
