[buildPlans.GitpIosevka_1]
family = "Gitp Iosevka 1"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.GitpIosevka_1.variants]
  inherits = "ss15"

[buildPlans.GitpIosevka_1.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.GitpIosevka_1.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.GitpIosevka_1.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.GitpIosevka_1.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.GitpIosevka_1.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.GitpIosevka_1.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.GitpIosevka_1.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.GitpIosevka_1.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.GitpIosevka_1.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.GitpIosevka_1.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.GitpIosevka_1.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.GitpIosevka_1.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"
